#!/bin/sh

echo "Analytics ID: $GA_ID"
#cd node_modules/typedoc-theme-transistor && grunt
cd ../../typedoc-theme-transistor && grunt
#cd ../..
#typedoc --out docs --includeDeclarations --excludeExternals --listInvalidSymbolLinks --name "React Native Background Geolocation" --theme ./node_modules/typedoc-theme-transistor/src/default --mode file --gaID $GA_ID --gaSite "auto" ./src/declarations/

pwd

../nodeXmms/node_modules/typedoc/bin/typedoc --out docs --includeDeclarations --excludeExternals --listInvalidSymbolLinks --name "React Native Background Geolocation" --theme ../nodeXmms/node_modules/typedoc-theme-transistor/src/default --mode file --gaID $GA_ID --gaSite "auto" ./src/declarations/

#cp ./node_modules/typedoc-theme-transistor/bin/default/assets/css/main.css ./docs/assets/css/main.css
pwd
cp bin/default/assets/css/main.css ../nodeXmms/docs/assets/css/main.css
cp ../nodeXmms/docs/globals.html ../nodeXmms/docs/index.html
touch ../nodeXmms/docs/.nojekyll

